# CHANGED BY CHRISTIAN ALEXANDER BAHRDT
# This file is derivative from the following file 
# https://github.com/edgexfoundry/device-sdk-go/blob/edinburgh/example/cmd/device-simple/res/configuration.toml
[Writable]
LogLevel = 'DEBUG'

[Service]
Host = "192.168.178.20"
Port = 49995
ConnectRetries = 20
Labels = []
OpenMsg = "device-bitflow started"
Timeout = 5000
EnableAsyncReadings = true
AsyncBufferSize = 16

[Registry]
Host = "localhost"
Port = 8500
Type = "consul"
CheckInterval = "10s"
FailLimit = 3
FailWaitTime = 10

[Clients]
  [Clients.Data]
  Name = "edgex-core-data"
  Protocol = "http"
  Host = "localhost"
  Port = 48080
  Timeout = 5000

  [Clients.Metadata]
  Name = "edgex-core-metadata"
  Protocol = "http"
  Host = "localhost"
  Port = 48081
  Timeout = 5000

  [Clients.Logging]
  Name = "edgex-support-logging"
  Protocol = "http"
  Host = "localhost"
  Port = 48061

[Device]
  DataTransform = true
  InitCmd = ""
  InitCmdArgs = ""
  MaxCmdOps = 128
  MaxCmdValueLen = 256
  RemoveCmd = ""
  RemoveCmdArgs = ""
  ProfilesDir = "./res"

[Logging]
EnableRemote = false
File = "./device-bitflow.log"

# Pre-define Devices
#[[DeviceList]]
#  Name = "Bitflow-Script-Test-Device"
#  Profile = "Bitflow-Script-Execution-Engine"
#  Description = "A full-manual bitflow script test device."
#  Labels = [ "industrial" ]
#  [DeviceList.Protocols]
#    [DeviceList.Protocols.other]
#      Address = "bitflow_script_test_device"
#      Port = "300"
#  [[DeviceList.AutoEvents]]
#    Frequency = "10s"
#    OnChange = false
#    Resource = "Switch"
#  [[DeviceList.AutoEvents]]
#    Frequency = "30s"
#    OnChange = false
#    Resource = "Image"
[Driver]
BrokerSchema = "tcp"
BrokerHost = "192.168.178.20"
BrokerPort = "1883"
CoreDataSchema = "http"
CoreDataHost = "192.168.178.20"
CoreDataPort = "48080"
ExportClientDataSchema = "http"
ExportClientHost = "192.168.178.20"
ExportClientPort = "48071"
